spring:
  application:
    name: kotlin-spring
  datasource:
    url: "jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.kiprbdrzcsbfdfwjkieg&password=GHmYZLKXxH6rrd6m"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
